### ISSUE TITLE
How you can show the updated graph?

### ISSUE THREAD

**Issue by ChetanAtrawalkarCA** [Programmer-RD-AI/Bitcoin-Price-Prediction-Learning-PyTorch-RNN#1]

**Comment by Programmer-RD-AI** [comment]
hi thanks for adding a issue.
the predicted Graph is logged to this link
https://wandb.ai/ranuga-d/Bitcoin-Price-Prediction

**Comment by Programmer-RD-AI** [comment]
Does that answer your question ? I am still working on this project so there is not logs

**Comment by ChetanAtrawalkarCA** [comment]
Yup and i'm so excited for this project, and BTW i'm also work on crypto app for users.

**Comment by Programmer-RD-AI** [comment]
ok, thank you, ok cool

**Comment by Programmer-RD-AI** [comment]
I am doing this project to learn about PyTorch RNN

**Comment by ChetanAtrawalkarCA** [comment]
Nice, writing optimal code in PyTorch is MUCH easier
